# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kcg_ui.ui'
#
# Created: Mon Mar  1 09:05:17 2021
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(921, 856)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.plot1 = dataplot_mpl(self.centralwidget)
        self.plot1.setMinimumSize(QtCore.QSize(0, 200))
        self.plot1.setObjectName(_fromUtf8("plot1"))
        self.horizontalLayout.addWidget(self.plot1)
        self.plot2 = dataplot_mpl(self.centralwidget)
        self.plot2.setMinimumSize(QtCore.QSize(0, 200))
        self.plot2.setObjectName(_fromUtf8("plot2"))
        self.horizontalLayout.addWidget(self.plot2)
        self.plot3 = dataplot_mpl(self.centralwidget)
        self.plot3.setMinimumSize(QtCore.QSize(0, 200))
        self.plot3.setObjectName(_fromUtf8("plot3"))
        self.horizontalLayout.addWidget(self.plot3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_config = QtGui.QWidget()
        self.tab_config.setObjectName(_fromUtf8("tab_config"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.tab_config)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 581, 80))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label = QtGui.QLabel(self.formLayoutWidget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.le_polling_interval = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.le_polling_interval.setObjectName(_fromUtf8("le_polling_interval"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.le_polling_interval)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.le_data_directory = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.le_data_directory.setObjectName(_fromUtf8("le_data_directory"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.le_data_directory)
        self.tabWidget.addTab(self.tab_config, _fromUtf8(""))
        self.tab_he3_2 = QtGui.QWidget()
        self.tab_he3_2.setObjectName(_fromUtf8("tab_he3_2"))
        self.gb1 = QtGui.QGroupBox(self.tab_he3_2)
        self.gb1.setGeometry(QtCore.QRect(10, 290, 211, 191))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb1.sizePolicy().hasHeightForWidth())
        self.gb1.setSizePolicy(sizePolicy)
        self.gb1.setMinimumSize(QtCore.QSize(0, 0))
        self.gb1.setFlat(False)
        self.gb1.setCheckable(False)
        self.gb1.setObjectName(_fromUtf8("gb1"))
        self.pb_enable_cryocon_control = QtGui.QPushButton(self.gb1)
        self.pb_enable_cryocon_control.setGeometry(QtCore.QRect(10, 140, 85, 27))
        self.pb_enable_cryocon_control.setMinimumSize(QtCore.QSize(85, 0))
        self.pb_enable_cryocon_control.setObjectName(_fromUtf8("pb_enable_cryocon_control"))
        self.pb_disable_cryocon_control = QtGui.QPushButton(self.gb1)
        self.pb_disable_cryocon_control.setGeometry(QtCore.QRect(110, 140, 85, 27))
        self.pb_disable_cryocon_control.setMinimumSize(QtCore.QSize(85, 0))
        self.pb_disable_cryocon_control.setObjectName(_fromUtf8("pb_disable_cryocon_control"))
        self.l_cryocon_control_status = QtGui.QLabel(self.gb1)
        self.l_cryocon_control_status.setGeometry(QtCore.QRect(120, 110, 41, 21))
        self.l_cryocon_control_status.setObjectName(_fromUtf8("l_cryocon_control_status"))
        self.pb_write_cryocon_control = QtGui.QPushButton(self.gb1)
        self.pb_write_cryocon_control.setGeometry(QtCore.QRect(10, 110, 95, 24))
        self.pb_write_cryocon_control.setObjectName(_fromUtf8("pb_write_cryocon_control"))
        self.formLayoutWidget_7 = QtGui.QWidget(self.gb1)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(10, 30, 191, 71))
        self.formLayoutWidget_7.setObjectName(_fromUtf8("formLayoutWidget_7"))
        self.formLayout_7 = QtGui.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_7.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setMargin(0)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.l1 = QtGui.QLabel(self.formLayoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l1.sizePolicy().hasHeightForWidth())
        self.l1.setSizePolicy(sizePolicy)
        self.l1.setMinimumSize(QtCore.QSize(111, 0))
        self.l1.setObjectName(_fromUtf8("l1"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.l1)
        self.l2 = QtGui.QLabel(self.formLayoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l2.sizePolicy().hasHeightForWidth())
        self.l2.setSizePolicy(sizePolicy)
        self.l2.setMinimumSize(QtCore.QSize(127, 0))
        self.l2.setMaximumSize(QtCore.QSize(16777215, 17))
        self.l2.setObjectName(_fromUtf8("l2"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.LabelRole, self.l2)
        self.le_charcoal_setpoint = QtGui.QLineEdit(self.formLayoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_charcoal_setpoint.sizePolicy().hasHeightForWidth())
        self.le_charcoal_setpoint.setSizePolicy(sizePolicy)
        self.le_charcoal_setpoint.setMinimumSize(QtCore.QSize(0, 0))
        self.le_charcoal_setpoint.setObjectName(_fromUtf8("le_charcoal_setpoint"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self.le_charcoal_setpoint)
        self.le_upper_setpoint = QtGui.QLineEdit(self.formLayoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_upper_setpoint.sizePolicy().hasHeightForWidth())
        self.le_upper_setpoint.setSizePolicy(sizePolicy)
        self.le_upper_setpoint.setMinimumSize(QtCore.QSize(0, 0))
        self.le_upper_setpoint.setMaxLength(32767)
        self.le_upper_setpoint.setObjectName(_fromUtf8("le_upper_setpoint"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.le_upper_setpoint)
        self.plot_he3 = dataplot_mpl(self.tab_he3_2)
        self.plot_he3.setGeometry(QtCore.QRect(420, 140, 471, 341))
        self.plot_he3.setObjectName(_fromUtf8("plot_he3"))
        self.gb2 = QtGui.QGroupBox(self.tab_he3_2)
        self.gb2.setGeometry(QtCore.QRect(230, 10, 601, 131))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb2.sizePolicy().hasHeightForWidth())
        self.gb2.setSizePolicy(sizePolicy)
        self.gb2.setMinimumSize(QtCore.QSize(0, 0))
        self.gb2.setObjectName(_fromUtf8("gb2"))
        self.layoutWidget = QtGui.QWidget(self.gb2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 25, 321, 95))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.l4 = QtGui.QLabel(self.layoutWidget)
        self.l4.setMinimumSize(QtCore.QSize(54, 0))
        self.l4.setObjectName(_fromUtf8("l4"))
        self.gridLayout_2.addWidget(self.l4, 0, 0, 1, 1)
        self.l_pot_hs_status = QtGui.QLabel(self.layoutWidget)
        self.l_pot_hs_status.setMinimumSize(QtCore.QSize(51, 0))
        self.l_pot_hs_status.setObjectName(_fromUtf8("l_pot_hs_status"))
        self.gridLayout_2.addWidget(self.l_pot_hs_status, 0, 1, 1, 1)
        self.pb_close_adr_hs = QtGui.QPushButton(self.layoutWidget)
        self.pb_close_adr_hs.setMinimumSize(QtCore.QSize(85, 0))
        self.pb_close_adr_hs.setObjectName(_fromUtf8("pb_close_adr_hs"))
        self.gridLayout_2.addWidget(self.pb_close_adr_hs, 1, 3, 1, 1)
        self.pb_open_pot_hs = QtGui.QPushButton(self.layoutWidget)
        self.pb_open_pot_hs.setMinimumSize(QtCore.QSize(85, 0))
        self.pb_open_pot_hs.setObjectName(_fromUtf8("pb_open_pot_hs"))
        self.gridLayout_2.addWidget(self.pb_open_pot_hs, 0, 2, 1, 1)
        self.pb_open_adr_hs = QtGui.QPushButton(self.layoutWidget)
        self.pb_open_adr_hs.setMinimumSize(QtCore.QSize(85, 0))
        self.pb_open_adr_hs.setObjectName(_fromUtf8("pb_open_adr_hs"))
        self.gridLayout_2.addWidget(self.pb_open_adr_hs, 1, 2, 1, 1)
        self.pb_close_pot_hs = QtGui.QPushButton(self.layoutWidget)
        self.pb_close_pot_hs.setMinimumSize(QtCore.QSize(85, 0))
        self.pb_close_pot_hs.setObjectName(_fromUtf8("pb_close_pot_hs"))
        self.gridLayout_2.addWidget(self.pb_close_pot_hs, 0, 3, 1, 1)
        self.l_adr_hs_status = QtGui.QLabel(self.layoutWidget)
        self.l_adr_hs_status.setMinimumSize(QtCore.QSize(37, 0))
        self.l_adr_hs_status.setObjectName(_fromUtf8("l_adr_hs_status"))
        self.gridLayout_2.addWidget(self.l_adr_hs_status, 1, 1, 1, 1)
        self.l3 = QtGui.QLabel(self.layoutWidget)
        self.l3.setMinimumSize(QtCore.QSize(27, 0))
        self.l3.setObjectName(_fromUtf8("l3"))
        self.gridLayout_2.addWidget(self.l3, 1, 0, 1, 1)
        self.l5 = QtGui.QLabel(self.layoutWidget)
        self.l5.setObjectName(_fromUtf8("l5"))
        self.gridLayout_2.addWidget(self.l5, 2, 0, 1, 1)
        self.l_charcoal_hs_status = QtGui.QLabel(self.layoutWidget)
        self.l_charcoal_hs_status.setObjectName(_fromUtf8("l_charcoal_hs_status"))
        self.gridLayout_2.addWidget(self.l_charcoal_hs_status, 2, 1, 1, 1)
        self.pb_open_charcoal_hs = QtGui.QPushButton(self.layoutWidget)
        self.pb_open_charcoal_hs.setObjectName(_fromUtf8("pb_open_charcoal_hs"))
        self.gridLayout_2.addWidget(self.pb_open_charcoal_hs, 2, 2, 1, 1)
        self.pb_close_charcoal_hs = QtGui.QPushButton(self.layoutWidget)
        self.pb_close_charcoal_hs.setObjectName(_fromUtf8("pb_close_charcoal_hs"))
        self.gridLayout_2.addWidget(self.pb_close_charcoal_hs, 2, 3, 1, 1)
        self.pb_charcoal_hs_move_relative = QtGui.QPushButton(self.gb2)
        self.pb_charcoal_hs_move_relative.setGeometry(QtCore.QRect(490, 30, 101, 27))
        self.pb_charcoal_hs_move_relative.setObjectName(_fromUtf8("pb_charcoal_hs_move_relative"))
        self.le_charcoal_num_turns = QtGui.QLineEdit(self.gb2)
        self.le_charcoal_num_turns.setGeometry(QtCore.QRect(390, 30, 85, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_charcoal_num_turns.sizePolicy().hasHeightForWidth())
        self.le_charcoal_num_turns.setSizePolicy(sizePolicy)
        self.le_charcoal_num_turns.setMinimumSize(QtCore.QSize(85, 0))
        self.le_charcoal_num_turns.setObjectName(_fromUtf8("le_charcoal_num_turns"))
        self.l29 = QtGui.QLabel(self.gb2)
        self.l29.setGeometry(QtCore.QRect(340, 40, 58, 17))
        self.l29.setObjectName(_fromUtf8("l29"))
        self.l_charcoal_position = QtGui.QLabel(self.gb2)
        self.l_charcoal_position.setGeometry(QtCore.QRect(340, 70, 91, 17))
        self.l_charcoal_position.setObjectName(_fromUtf8("l_charcoal_position"))
        self.pb_charcoal_position_reset = QtGui.QPushButton(self.gb2)
        self.pb_charcoal_position_reset.setGeometry(QtCore.QRect(490, 60, 101, 27))
        self.pb_charcoal_position_reset.setObjectName(_fromUtf8("pb_charcoal_position_reset"))
        self.gb_charcoal_close = QtGui.QGroupBox(self.tab_he3_2)
        self.gb_charcoal_close.setGeometry(QtCore.QRect(10, 10, 211, 271))
        self.gb_charcoal_close.setObjectName(_fromUtf8("gb_charcoal_close"))
        self.formLayoutWidget_3 = QtGui.QWidget(self.gb_charcoal_close)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 193, 194))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_3 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.le_charcoal_close_fast_turns = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.le_charcoal_close_fast_turns.setObjectName(_fromUtf8("le_charcoal_close_fast_turns"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.le_charcoal_close_fast_turns)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.le_charcoal_close_stage1_turns = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.le_charcoal_close_stage1_turns.setObjectName(_fromUtf8("le_charcoal_close_stage1_turns"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.le_charcoal_close_stage1_turns)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.le_charcoal_close_stage1_temp = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.le_charcoal_close_stage1_temp.setObjectName(_fromUtf8("le_charcoal_close_stage1_temp"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.le_charcoal_close_stage1_temp)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_6)
        self.le_charcoal_close_stage2_temp = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.le_charcoal_close_stage2_temp.setObjectName(_fromUtf8("le_charcoal_close_stage2_temp"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.le_charcoal_close_stage2_temp)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_7)
        self.le_charcoal_close_full_close_temp = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.le_charcoal_close_full_close_temp.setObjectName(_fromUtf8("le_charcoal_close_full_close_temp"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.le_charcoal_close_full_close_temp)
        self.label_12 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_12)
        self.le_charcoal_close_step_time = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.le_charcoal_close_step_time.setObjectName(_fromUtf8("le_charcoal_close_step_time"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.le_charcoal_close_step_time)
        self.pb_charcoal_close_start = QtGui.QPushButton(self.gb_charcoal_close)
        self.pb_charcoal_close_start.setGeometry(QtCore.QRect(10, 230, 87, 27))
        self.pb_charcoal_close_start.setObjectName(_fromUtf8("pb_charcoal_close_start"))
        self.l_slow_charcoal_close_status = QtGui.QLabel(self.gb_charcoal_close)
        self.l_slow_charcoal_close_status.setGeometry(QtCore.QRect(110, 230, 91, 17))
        self.l_slow_charcoal_close_status.setObjectName(_fromUtf8("l_slow_charcoal_close_status"))
        self.gb_he3_test = QtGui.QGroupBox(self.tab_he3_2)
        self.gb_he3_test.setGeometry(QtCore.QRect(230, 160, 181, 231))
        self.gb_he3_test.setObjectName(_fromUtf8("gb_he3_test"))
        self.pb_he3_test_start = QtGui.QPushButton(self.gb_he3_test)
        self.pb_he3_test_start.setGeometry(QtCore.QRect(10, 190, 85, 27))
        self.pb_he3_test_start.setMinimumSize(QtCore.QSize(85, 0))
        self.pb_he3_test_start.setObjectName(_fromUtf8("pb_he3_test_start"))
        self.formLayoutWidget_6 = QtGui.QWidget(self.gb_he3_test)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(10, 30, 161, 156))
        self.formLayoutWidget_6.setObjectName(_fromUtf8("formLayoutWidget_6"))
        self.formLayout_6 = QtGui.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_6.setMargin(0)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label_14 = QtGui.QLabel(self.formLayoutWidget_6)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_14)
        self.le_he3_test_hold_time = QtGui.QLineEdit(self.formLayoutWidget_6)
        self.le_he3_test_hold_time.setObjectName(_fromUtf8("le_he3_test_hold_time"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.le_he3_test_hold_time)
        self.label_15 = QtGui.QLabel(self.formLayoutWidget_6)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_15)
        self.le_he3_test_heat_start_temp = QtGui.QLineEdit(self.formLayoutWidget_6)
        self.le_he3_test_heat_start_temp.setObjectName(_fromUtf8("le_he3_test_heat_start_temp"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.le_he3_test_heat_start_temp)
        self.label_16 = QtGui.QLabel(self.formLayoutWidget_6)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_16)
        self.le_he3_test_heat_stop_temp = QtGui.QLineEdit(self.formLayoutWidget_6)
        self.le_he3_test_heat_stop_temp.setObjectName(_fromUtf8("le_he3_test_heat_stop_temp"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.FieldRole, self.le_he3_test_heat_stop_temp)
        self.cb_he3_test_apply_heat = QtGui.QCheckBox(self.formLayoutWidget_6)
        self.cb_he3_test_apply_heat.setObjectName(_fromUtf8("cb_he3_test_apply_heat"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.cb_he3_test_apply_heat)
        self.label_17 = QtGui.QLabel(self.formLayoutWidget_6)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_6.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_17)
        self.le_he3_test_voltage = QtGui.QLineEdit(self.formLayoutWidget_6)
        self.le_he3_test_voltage.setObjectName(_fromUtf8("le_he3_test_voltage"))
        self.formLayout_6.setWidget(4, QtGui.QFormLayout.FieldRole, self.le_he3_test_voltage)
        self.tabWidget.addTab(self.tab_he3_2, _fromUtf8(""))
        self.tab_adr = QtGui.QWidget()
        self.tab_adr.setObjectName(_fromUtf8("tab_adr"))
        self.gb_ramp = QtGui.QGroupBox(self.tab_adr)
        self.gb_ramp.setGeometry(QtCore.QRect(10, 80, 241, 291))
        self.gb_ramp.setObjectName(_fromUtf8("gb_ramp"))
        self.pb_ramp_careful = QtGui.QPushButton(self.gb_ramp)
        self.pb_ramp_careful.setGeometry(QtCore.QRect(10, 250, 95, 24))
        self.pb_ramp_careful.setObjectName(_fromUtf8("pb_ramp_careful"))
        self.formLayoutWidget = QtGui.QWidget(self.gb_ramp)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 224, 217))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.l_7 = QtGui.QLabel(self.formLayoutWidget)
        self.l_7.setObjectName(_fromUtf8("l_7"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.l_7)
        self.l_ramp_current_level = QtGui.QLabel(self.formLayoutWidget)
        self.l_ramp_current_level.setObjectName(_fromUtf8("l_ramp_current_level"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.l_ramp_current_level)
        self.l_8 = QtGui.QLabel(self.formLayoutWidget)
        self.l_8.setObjectName(_fromUtf8("l_8"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.l_8)
        self.le_ramp_target_level = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_ramp_target_level.setObjectName(_fromUtf8("le_ramp_target_level"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.le_ramp_target_level)
        self.l_9 = QtGui.QLabel(self.formLayoutWidget)
        self.l_9.setObjectName(_fromUtf8("l_9"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.l_9)
        self.le_ramp_time = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_ramp_time.setObjectName(_fromUtf8("le_ramp_time"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.le_ramp_time)
        self.l_10 = QtGui.QLabel(self.formLayoutWidget)
        self.l_10.setObjectName(_fromUtf8("l_10"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.l_10)
        self.le_ramp_step_time = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_ramp_step_time.setObjectName(_fromUtf8("le_ramp_step_time"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.le_ramp_step_time)
        self.l_11 = QtGui.QLabel(self.formLayoutWidget)
        self.l_11.setObjectName(_fromUtf8("l_11"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.l_11)
        self.le_ramp_start_temp = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_ramp_start_temp.setObjectName(_fromUtf8("le_ramp_start_temp"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.le_ramp_start_temp)
        self.l_12 = QtGui.QLabel(self.formLayoutWidget)
        self.l_12.setObjectName(_fromUtf8("l_12"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.l_12)
        self.le_ramp_max_temp = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_ramp_max_temp.setObjectName(_fromUtf8("le_ramp_max_temp"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.le_ramp_max_temp)
        self.l_13 = QtGui.QLabel(self.formLayoutWidget)
        self.l_13.setObjectName(_fromUtf8("l_13"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.l_13)
        self.le_ramp_soak_time = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_ramp_soak_time.setObjectName(_fromUtf8("le_ramp_soak_time"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.le_ramp_soak_time)
        self.pb_ramp = QtGui.QPushButton(self.gb_ramp)
        self.pb_ramp.setGeometry(QtCore.QRect(110, 250, 101, 24))
        self.pb_ramp.setObjectName(_fromUtf8("pb_ramp"))
        self.gb_ramp_down = QtGui.QGroupBox(self.tab_adr)
        self.gb_ramp_down.setGeometry(QtCore.QRect(280, 80, 211, 231))
        self.gb_ramp_down.setObjectName(_fromUtf8("gb_ramp_down"))
        self.formLayoutWidget_4 = QtGui.QWidget(self.gb_ramp_down)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 194, 171))
        self.formLayoutWidget_4.setObjectName(_fromUtf8("formLayoutWidget_4"))
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setMargin(0)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_8 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.le_mag_ramp_down_precool_temp = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.le_mag_ramp_down_precool_temp.setObjectName(_fromUtf8("le_mag_ramp_down_precool_temp"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.le_mag_ramp_down_precool_temp)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_9)
        self.le_mag_ramp_down_target_level = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.le_mag_ramp_down_target_level.setObjectName(_fromUtf8("le_mag_ramp_down_target_level"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.le_mag_ramp_down_target_level)
        self.label_10 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_10)
        self.le_mag_ramp_down_ramp_time = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.le_mag_ramp_down_ramp_time.setObjectName(_fromUtf8("le_mag_ramp_down_ramp_time"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.le_mag_ramp_down_ramp_time)
        self.label_13 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_13)
        self.le_mag_ramp_down_settle_time = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.le_mag_ramp_down_settle_time.setObjectName(_fromUtf8("le_mag_ramp_down_settle_time"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.le_mag_ramp_down_settle_time)
        self.label_11 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_11)
        self.le_mag_ramp_down_step_time = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.le_mag_ramp_down_step_time.setObjectName(_fromUtf8("le_mag_ramp_down_step_time"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.le_mag_ramp_down_step_time)
        self.pb_ramp_down = QtGui.QPushButton(self.gb_ramp_down)
        self.pb_ramp_down.setGeometry(QtCore.QRect(10, 200, 87, 27))
        self.pb_ramp_down.setObjectName(_fromUtf8("pb_ramp_down"))
        self.l_ramp_status = QtGui.QLabel(self.tab_adr)
        self.l_ramp_status.setGeometry(QtCore.QRect(20, 420, 241, 31))
        self.l_ramp_status.setObjectName(_fromUtf8("l_ramp_status"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_adr)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 311, 51))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.pb_relay_control = QtGui.QPushButton(self.groupBox_2)
        self.pb_relay_control.setGeometry(QtCore.QRect(240, 20, 61, 24))
        self.pb_relay_control.setObjectName(_fromUtf8("pb_relay_control"))
        self.l_6 = QtGui.QLabel(self.groupBox_2)
        self.l_6.setGeometry(QtCore.QRect(10, 30, 51, 16))
        self.l_6.setObjectName(_fromUtf8("l_6"))
        self.l_relay_status = QtGui.QLabel(self.groupBox_2)
        self.l_relay_status.setGeometry(QtCore.QRect(100, 30, 71, 16))
        self.l_relay_status.setObjectName(_fromUtf8("l_relay_status"))
        self.pb_relay_ramp = QtGui.QPushButton(self.groupBox_2)
        self.pb_relay_ramp.setGeometry(QtCore.QRect(180, 20, 51, 24))
        self.pb_relay_ramp.setObjectName(_fromUtf8("pb_relay_ramp"))
        self.plot_kepco_voltage = dataplot_mpl(self.tab_adr)
        self.plot_kepco_voltage.setGeometry(QtCore.QRect(499, 10, 391, 220))
        self.plot_kepco_voltage.setMinimumSize(QtCore.QSize(200, 200))
        self.plot_kepco_voltage.setObjectName(_fromUtf8("plot_kepco_voltage"))
        self.plot_kepco_current = dataplot_mpl(self.tab_adr)
        self.plot_kepco_current.setGeometry(QtCore.QRect(499, 249, 391, 220))
        self.plot_kepco_current.setMinimumSize(QtCore.QSize(200, 200))
        self.plot_kepco_current.setObjectName(_fromUtf8("plot_kepco_current"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_adr)
        self.groupBox_3.setGeometry(QtCore.QRect(280, 320, 211, 131))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayoutWidget_5 = QtGui.QWidget(self.groupBox_3)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(10, 30, 189, 31))
        self.formLayoutWidget_5.setObjectName(_fromUtf8("formLayoutWidget_5"))
        self.formLayout_5 = QtGui.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setMargin(0)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.l_29 = QtGui.QLabel(self.formLayoutWidget_5)
        self.l_29.setObjectName(_fromUtf8("l_29"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.l_29)
        self.le_regulate_temp = QtGui.QLineEdit(self.formLayoutWidget_5)
        self.le_regulate_temp.setObjectName(_fromUtf8("le_regulate_temp"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.le_regulate_temp)
        self.pb_regulate_start = QtGui.QPushButton(self.groupBox_3)
        self.pb_regulate_start.setGeometry(QtCore.QRect(10, 70, 87, 27))
        self.pb_regulate_start.setObjectName(_fromUtf8("pb_regulate_start"))
        self.pb_regulate_stop = QtGui.QPushButton(self.groupBox_3)
        self.pb_regulate_stop.setGeometry(QtCore.QRect(110, 70, 87, 27))
        self.pb_regulate_stop.setObjectName(_fromUtf8("pb_regulate_stop"))
        self.l_regulate_status = QtGui.QLabel(self.groupBox_3)
        self.l_regulate_status.setGeometry(QtCore.QRect(10, 100, 71, 16))
        self.l_regulate_status.setObjectName(_fromUtf8("l_regulate_status"))
        self.tabWidget.addTab(self.tab_adr, _fromUtf8(""))
        self.tab_cycle = QtGui.QWidget()
        self.tab_cycle.setObjectName(_fromUtf8("tab_cycle"))
        self.pb_start_cycle_now = QtGui.QPushButton(self.tab_cycle)
        self.pb_start_cycle_now.setGeometry(QtCore.QRect(10, 90, 111, 24))
        self.pb_start_cycle_now.setObjectName(_fromUtf8("pb_start_cycle_now"))
        self.l_14 = QtGui.QLabel(self.tab_cycle)
        self.l_14.setGeometry(QtCore.QRect(20, 20, 67, 23))
        self.l_14.setObjectName(_fromUtf8("l_14"))
        self.dte_start_time = QtGui.QDateTimeEdit(self.tab_cycle)
        self.dte_start_time.setEnabled(False)
        self.dte_start_time.setGeometry(QtCore.QRect(100, 20, 149, 23))
        self.dte_start_time.setObjectName(_fromUtf8("dte_start_time"))
        self.cb_is_daily_cycle = QtGui.QCheckBox(self.tab_cycle)
        self.cb_is_daily_cycle.setEnabled(False)
        self.cb_is_daily_cycle.setGeometry(QtCore.QRect(20, 50, 86, 21))
        self.cb_is_daily_cycle.setObjectName(_fromUtf8("cb_is_daily_cycle"))
        self.pb_start_cycle_later = QtGui.QPushButton(self.tab_cycle)
        self.pb_start_cycle_later.setEnabled(False)
        self.pb_start_cycle_later.setGeometry(QtCore.QRect(100, 50, 111, 24))
        self.pb_start_cycle_later.setObjectName(_fromUtf8("pb_start_cycle_later"))
        self.groupBox = QtGui.QGroupBox(self.tab_cycle)
        self.groupBox.setGeometry(QtCore.QRect(290, 10, 331, 331))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 29, 313, 295))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.l_cycle_status_ramp_up = QtGui.QLabel(self.gridLayoutWidget)
        self.l_cycle_status_ramp_up.setObjectName(_fromUtf8("l_cycle_status_ramp_up"))
        self.gridLayout_3.addWidget(self.l_cycle_status_ramp_up, 13, 1, 1, 1)
        self.l_22 = QtGui.QLabel(self.gridLayoutWidget)
        self.l_22.setObjectName(_fromUtf8("l_22"))
        self.gridLayout_3.addWidget(self.l_22, 16, 0, 1, 1)
        self.l_15 = QtGui.QLabel(self.gridLayoutWidget)
        self.l_15.setObjectName(_fromUtf8("l_15"))
        self.gridLayout_3.addWidget(self.l_15, 7, 0, 1, 1)
        self.l_cycle_status_close_pot_hs = QtGui.QLabel(self.gridLayoutWidget)
        self.l_cycle_status_close_pot_hs.setObjectName(_fromUtf8("l_cycle_status_close_pot_hs"))
        self.gridLayout_3.addWidget(self.l_cycle_status_close_pot_hs, 8, 1, 1, 1)
        self.l_24 = QtGui.QLabel(self.gridLayoutWidget)
        self.l_24.setObjectName(_fromUtf8("l_24"))
        self.gridLayout_3.addWidget(self.l_24, 18, 0, 1, 1)
        self.l_17 = QtGui.QLabel(self.gridLayoutWidget)
        self.l_17.setObjectName(_fromUtf8("l_17"))
        self.gridLayout_3.addWidget(self.l_17, 10, 0, 1, 1)
        self.l_16 = QtGui.QLabel(self.gridLayoutWidget)
        self.l_16.setObjectName(_fromUtf8("l_16"))
        self.gridLayout_3.addWidget(self.l_16, 8, 0, 1, 1)
        self.l_18 = QtGui.QLabel(self.gridLayoutWidget)
        self.l_18.setObjectName(_fromUtf8("l_18"))
        self.gridLayout_3.addWidget(self.l_18, 7, 1, 1, 1)
        self.l_19 = QtGui.QLabel(self.gridLayoutWidget)
        self.l_19.setObjectName(_fromUtf8("l_19"))
        self.gridLayout_3.addWidget(self.l_19, 11, 0, 1, 1)
        self.l_20 = QtGui.QLabel(self.gridLayoutWidget)
        self.l_20.setObjectName(_fromUtf8("l_20"))
        self.gridLayout_3.addWidget(self.l_20, 13, 0, 1, 1)
        self.l_21 = QtGui.QLabel(self.gridLayoutWidget)
        self.l_21.setObjectName(_fromUtf8("l_21"))
        self.gridLayout_3.addWidget(self.l_21, 14, 0, 1, 1)
        self.l_23 = QtGui.QLabel(self.gridLayoutWidget)
        self.l_23.setObjectName(_fromUtf8("l_23"))
        self.gridLayout_3.addWidget(self.l_23, 17, 0, 1, 1)
        self.l_cycle_status_open_charcoal_hs = QtGui.QLabel(self.gridLayoutWidget)
        self.l_cycle_status_open_charcoal_hs.setObjectName(_fromUtf8("l_cycle_status_open_charcoal_hs"))
        self.gridLayout_3.addWidget(self.l_cycle_status_open_charcoal_hs, 10, 1, 1, 1)
        self.l_cycle_status_heat_charcoal = QtGui.QLabel(self.gridLayoutWidget)
        self.l_cycle_status_heat_charcoal.setObjectName(_fromUtf8("l_cycle_status_heat_charcoal"))
        self.gridLayout_3.addWidget(self.l_cycle_status_heat_charcoal, 11, 1, 1, 1)
        self.l_25 = QtGui.QLabel(self.gridLayoutWidget)
        self.l_25.setObjectName(_fromUtf8("l_25"))
        self.gridLayout_3.addWidget(self.l_25, 19, 0, 1, 1)
        self.l_26 = QtGui.QLabel(self.gridLayoutWidget)
        self.l_26.setObjectName(_fromUtf8("l_26"))
        self.gridLayout_3.addWidget(self.l_26, 15, 0, 1, 1)
        self.l_27 = QtGui.QLabel(self.gridLayoutWidget)
        self.l_27.setObjectName(_fromUtf8("l_27"))
        self.gridLayout_3.addWidget(self.l_27, 9, 0, 1, 1)
        self.l_cycle_status_close_adr_hs = QtGui.QLabel(self.gridLayoutWidget)
        self.l_cycle_status_close_adr_hs.setObjectName(_fromUtf8("l_cycle_status_close_adr_hs"))
        self.gridLayout_3.addWidget(self.l_cycle_status_close_adr_hs, 9, 1, 1, 1)
        self.l_cycle_status_soak = QtGui.QLabel(self.gridLayoutWidget)
        self.l_cycle_status_soak.setObjectName(_fromUtf8("l_cycle_status_soak"))
        self.gridLayout_3.addWidget(self.l_cycle_status_soak, 14, 1, 1, 1)
        self.l_28 = QtGui.QLabel(self.gridLayoutWidget)
        self.l_28.setObjectName(_fromUtf8("l_28"))
        self.gridLayout_3.addWidget(self.l_28, 12, 0, 1, 1)
        self.l_cycle_status_wait_cool_plate = QtGui.QLabel(self.gridLayoutWidget)
        self.l_cycle_status_wait_cool_plate.setObjectName(_fromUtf8("l_cycle_status_wait_cool_plate"))
        self.gridLayout_3.addWidget(self.l_cycle_status_wait_cool_plate, 12, 1, 1, 1)
        self.l_cycle_status_open_pot_hs = QtGui.QLabel(self.gridLayoutWidget)
        self.l_cycle_status_open_pot_hs.setObjectName(_fromUtf8("l_cycle_status_open_pot_hs"))
        self.gridLayout_3.addWidget(self.l_cycle_status_open_pot_hs, 15, 1, 1, 1)
        self.l_cycle_status_turn_off_charcoal = QtGui.QLabel(self.gridLayoutWidget)
        self.l_cycle_status_turn_off_charcoal.setObjectName(_fromUtf8("l_cycle_status_turn_off_charcoal"))
        self.gridLayout_3.addWidget(self.l_cycle_status_turn_off_charcoal, 16, 1, 1, 1)
        self.l_cycle_status_close_charcoal = QtGui.QLabel(self.gridLayoutWidget)
        self.l_cycle_status_close_charcoal.setObjectName(_fromUtf8("l_cycle_status_close_charcoal"))
        self.gridLayout_3.addWidget(self.l_cycle_status_close_charcoal, 17, 1, 1, 1)
        self.l_cycle_status_open_adr_hs = QtGui.QLabel(self.gridLayoutWidget)
        self.l_cycle_status_open_adr_hs.setObjectName(_fromUtf8("l_cycle_status_open_adr_hs"))
        self.gridLayout_3.addWidget(self.l_cycle_status_open_adr_hs, 18, 1, 1, 1)
        self.l_cycle_status_ramp_down_magnet = QtGui.QLabel(self.gridLayoutWidget)
        self.l_cycle_status_ramp_down_magnet.setObjectName(_fromUtf8("l_cycle_status_ramp_down_magnet"))
        self.gridLayout_3.addWidget(self.l_cycle_status_ramp_down_magnet, 19, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 3)
        self.gridLayout_3.setColumnStretch(1, 2)
        self.pb_stop_cycle = QtGui.QPushButton(self.tab_cycle)
        self.pb_stop_cycle.setEnabled(False)
        self.pb_stop_cycle.setGeometry(QtCore.QRect(10, 120, 111, 24))
        self.pb_stop_cycle.setObjectName(_fromUtf8("pb_stop_cycle"))
        self.tabWidget.addTab(self.tab_cycle, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 921, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Polling Interval (s)", None))
        self.le_polling_interval.setText(_translate("MainWindow", "4", None))
        self.label_2.setText(_translate("MainWindow", "Data Directory", None))
        self.le_data_directory.setText(_translate("MainWindow", "/data3/temp_data/", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_config), _translate("MainWindow", "Config", None))
        self.gb1.setTitle(_translate("MainWindow", "Cryocon Control", None))
        self.pb_enable_cryocon_control.setText(_translate("MainWindow", "Enable", None))
        self.pb_disable_cryocon_control.setText(_translate("MainWindow", "Disable", None))
        self.l_cryocon_control_status.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">OFF</span></p></body></html>", None))
        self.pb_write_cryocon_control.setText(_translate("MainWindow", "Write", None))
        self.l1.setText(_translate("MainWindow", "Upper Setpoint (K)", None))
        self.l2.setText(_translate("MainWindow", "Charcoal Setpoint (K)", None))
        self.le_charcoal_setpoint.setText(_translate("MainWindow", "55", None))
        self.le_upper_setpoint.setText(_translate("MainWindow", "5", None))
        self.gb2.setTitle(_translate("MainWindow", "Heatswitch Control", None))
        self.l4.setText(_translate("MainWindow", "Pot", None))
        self.l_pot_hs_status.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">???</span></p></body></html>", None))
        self.pb_close_adr_hs.setText(_translate("MainWindow", "Close", None))
        self.pb_open_pot_hs.setText(_translate("MainWindow", "Open", None))
        self.pb_open_adr_hs.setText(_translate("MainWindow", "Open", None))
        self.pb_close_pot_hs.setText(_translate("MainWindow", "Close", None))
        self.l_adr_hs_status.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">???</span></p></body></html>", None))
        self.l3.setText(_translate("MainWindow", "ADR", None))
        self.l5.setText(_translate("MainWindow", "Charcoal", None))
        self.l_charcoal_hs_status.setText(_translate("MainWindow", "<b>???</b>", None))
        self.pb_open_charcoal_hs.setText(_translate("MainWindow", "Open", None))
        self.pb_close_charcoal_hs.setText(_translate("MainWindow", "Close", None))
        self.pb_charcoal_hs_move_relative.setText(_translate("MainWindow", "Move Relative", None))
        self.le_charcoal_num_turns.setText(_translate("MainWindow", "-0.05", None))
        self.l29.setText(_translate("MainWindow", "Turns:", None))
        self.l_charcoal_position.setText(_translate("MainWindow", "Position: 0", None))
        self.pb_charcoal_position_reset.setText(_translate("MainWindow", "Reset Position", None))
        self.gb_charcoal_close.setTitle(_translate("MainWindow", "Slow Charcoal Close", None))
        self.label_3.setText(_translate("MainWindow", "Fast Turns", None))
        self.le_charcoal_close_fast_turns.setText(_translate("MainWindow", "5", None))
        self.label_4.setText(_translate("MainWindow", "Stage 1 Turns", None))
        self.le_charcoal_close_stage1_turns.setText(_translate("MainWindow", "1", None))
        self.label_5.setText(_translate("MainWindow", "Stage 1 Temp (K)", None))
        self.le_charcoal_close_stage1_temp.setText(_translate("MainWindow", "3.8", None))
        self.label_6.setText(_translate("MainWindow", "Stage 2 Temp (K)", None))
        self.le_charcoal_close_stage2_temp.setText(_translate("MainWindow", "5.0", None))
        self.label_7.setText(_translate("MainWindow", "Full Close Temp (K)", None))
        self.le_charcoal_close_full_close_temp.setText(_translate("MainWindow", "10.0", None))
        self.label_12.setText(_translate("MainWindow", "Step Time (s)", None))
        self.le_charcoal_close_step_time.setText(_translate("MainWindow", "10.0", None))
        self.pb_charcoal_close_start.setText(_translate("MainWindow", "Start", None))
        self.l_slow_charcoal_close_status.setText(_translate("MainWindow", "???", None))
        self.gb_he3_test.setTitle(_translate("MainWindow", "He-3 Cycle", None))
        self.pb_he3_test_start.setText(_translate("MainWindow", "Start", None))
        self.label_14.setText(_translate("MainWindow", "Hold Time (min):", None))
        self.le_he3_test_hold_time.setText(_translate("MainWindow", "30", None))
        self.label_15.setText(_translate("MainWindow", "Heat Start Temp (K):", None))
        self.le_he3_test_heat_start_temp.setText(_translate("MainWindow", "0.5", None))
        self.label_16.setText(_translate("MainWindow", "Heat Stop Temp (K):", None))
        self.le_he3_test_heat_stop_temp.setText(_translate("MainWindow", "1.0", None))
        self.cb_he3_test_apply_heat.setText(_translate("MainWindow", "Apply Heat", None))
        self.label_17.setText(_translate("MainWindow", "Heater Voltage (V):", None))
        self.le_he3_test_voltage.setText(_translate("MainWindow", "1.0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_he3_2), _translate("MainWindow", "He 3", None))
        self.gb_ramp.setTitle(_translate("MainWindow", "Ramp Up", None))
        self.pb_ramp_careful.setText(_translate("MainWindow", "Careful Ramp", None))
        self.l_7.setText(_translate("MainWindow", "Current Level (%):", None))
        self.l_ramp_current_level.setText(_translate("MainWindow", "0", None))
        self.l_8.setText(_translate("MainWindow", "Target Level (%):", None))
        self.le_ramp_target_level.setText(_translate("MainWindow", "90", None))
        self.l_9.setText(_translate("MainWindow", "Total Time (min):", None))
        self.le_ramp_time.setText(_translate("MainWindow", "30", None))
        self.l_10.setText(_translate("MainWindow", "Step Time (s):", None))
        self.le_ramp_step_time.setText(_translate("MainWindow", "5", None))
        self.l_11.setText(_translate("MainWindow", "3K Plate Start Temp (K):", None))
        self.le_ramp_start_temp.setText(_translate("MainWindow", "3.2", None))
        self.l_12.setText(_translate("MainWindow", "Max 3K Temp (K):", None))
        self.le_ramp_max_temp.setText(_translate("MainWindow", "6.0", None))
        self.l_13.setText(_translate("MainWindow", "Soak Time (min)", None))
        self.le_ramp_soak_time.setText(_translate("MainWindow", "180", None))
        self.pb_ramp.setText(_translate("MainWindow", "Ramp", None))
        self.gb_ramp_down.setTitle(_translate("MainWindow", "Ramp Down", None))
        self.label_8.setText(_translate("MainWindow", "ADR Start Temp (K)", None))
        self.le_mag_ramp_down_precool_temp.setText(_translate("MainWindow", "1.0", None))
        self.label_9.setText(_translate("MainWindow", "Target Level (%)", None))
        self.le_mag_ramp_down_target_level.setText(_translate("MainWindow", "0", None))
        self.label_10.setText(_translate("MainWindow", "Total Time (min)", None))
        self.le_mag_ramp_down_ramp_time.setText(_translate("MainWindow", "30", None))
        self.label_13.setText(_translate("MainWindow", "Settle Time (s)", None))
        self.le_mag_ramp_down_settle_time.setText(_translate("MainWindow", "120", None))
        self.label_11.setText(_translate("MainWindow", "Step Time (s)", None))
        self.le_mag_ramp_down_step_time.setText(_translate("MainWindow", "5.0", None))
        self.pb_ramp_down.setText(_translate("MainWindow", "Start", None))
        self.l_ramp_status.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Waiting for start temp</span></p></body></html>", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Relay Control", None))
        self.pb_relay_control.setText(_translate("MainWindow", "Control", None))
        self.l_6.setText(_translate("MainWindow", " Status:", None))
        self.l_relay_status.setText(_translate("MainWindow", "<b>???<b>", None))
        self.pb_relay_ramp.setText(_translate("MainWindow", "Ramp", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Regulate Temperature", None))
        self.l_29.setText(_translate("MainWindow", "Temperature (mK)", None))
        self.le_regulate_temp.setText(_translate("MainWindow", "130", None))
        self.pb_regulate_start.setText(_translate("MainWindow", "Start", None))
        self.pb_regulate_stop.setText(_translate("MainWindow", "Stop", None))
        self.l_regulate_status.setText(_translate("MainWindow", "<b>???<b>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_adr), _translate("MainWindow", "ADR", None))
        self.pb_start_cycle_now.setText(_translate("MainWindow", "Start Cycle Now", None))
        self.l_14.setText(_translate("MainWindow", "Start Time:", None))
        self.cb_is_daily_cycle.setText(_translate("MainWindow", "Daily", None))
        self.pb_start_cycle_later.setText(_translate("MainWindow", "Start Cycle Later", None))
        self.groupBox.setTitle(_translate("MainWindow", "Cycle Status", None))
        self.l_cycle_status_ramp_up.setText(_translate("MainWindow", "???", None))
        self.l_22.setText(_translate("MainWindow", "Turn off Charcoal Power", None))
        self.l_15.setText(_translate("MainWindow", "<b>Step</b>", None))
        self.l_cycle_status_close_pot_hs.setText(_translate("MainWindow", "???", None))
        self.l_24.setText(_translate("MainWindow", "Open ADR Heat Switch", None))
        self.l_17.setText(_translate("MainWindow", "Open Charcoal Heat Swtich", None))
        self.l_16.setText(_translate("MainWindow", "Close Pot Heat Switch", None))
        self.l_18.setText(_translate("MainWindow", "<b>Status</b>", None))
        self.l_19.setText(_translate("MainWindow", "Heat Charcoal", None))
        self.l_20.setText(_translate("MainWindow", "Ramp up Magnet", None))
        self.l_21.setText(_translate("MainWindow", "Soak Magnet", None))
        self.l_23.setText(_translate("MainWindow", "Close Charcoal Heat Switch", None))
        self.l_cycle_status_open_charcoal_hs.setText(_translate("MainWindow", "???", None))
        self.l_cycle_status_heat_charcoal.setText(_translate("MainWindow", "???", None))
        self.l_25.setText(_translate("MainWindow", "Ramp Down Magnet", None))
        self.l_26.setText(_translate("MainWindow", "Open Pot Heat Switch", None))
        self.l_27.setText(_translate("MainWindow", "Close ADR Heat Switch", None))
        self.l_cycle_status_close_adr_hs.setText(_translate("MainWindow", "???", None))
        self.l_cycle_status_soak.setText(_translate("MainWindow", "???", None))
        self.l_28.setText(_translate("MainWindow", "Wait for Cool plate", None))
        self.l_cycle_status_wait_cool_plate.setText(_translate("MainWindow", "???", None))
        self.l_cycle_status_open_pot_hs.setText(_translate("MainWindow", "???", None))
        self.l_cycle_status_turn_off_charcoal.setText(_translate("MainWindow", "???", None))
        self.l_cycle_status_close_charcoal.setText(_translate("MainWindow", "???", None))
        self.l_cycle_status_open_adr_hs.setText(_translate("MainWindow", "???", None))
        self.l_cycle_status_ramp_down_magnet.setText(_translate("MainWindow", "???", None))
        self.pb_stop_cycle.setText(_translate("MainWindow", "Stop Cycle", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cycle), _translate("MainWindow", "Cycle", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))

from dataplot_mpl import dataplot_mpl
